version: "3.9"

services:
  holo-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: holo-collector-ai-cpu
    restart: unless-stopped
    environment:
      UVICORN_WORKERS: 1
      PYTHONUNBUFFERED: 1
    ports:
      - "8101:8000"
    # volumes:
      # Falls du lokal schnell Modelle oder Code anpassen willst
      # - ./models:/app/models:ro
      # - ./app:/app/app:ro
